stages:
  - deploy

variables:
  GITHUB_USER: "yuvraajdjadhav"
  GITHUB_EMAIL: "yuvrajdjadhav@gmail.com"

deploy_to_github:
  stage: deploy
  script:
    - git config --global user.name "$GITHUB_USER"
    - git config --global user.email "$GITHUB_EMAIL"
    - git remote add github $GITHUB_REPO
    - git fetch origin
    - git checkout -b temp-branch
    - git pull origin main  # Adjust if your main branch is different
    - git push github temp-branch:main  # Adjust if your main branch is different
  only:
    - main  # This triggers the job only on changes to the main branch update
